apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9898"
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:6.5.0
        ports:
        - containerPort: 9898
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
